name: Run

on:
  schedule:
    - cron: '0 0 */1 * *'
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install Node.js dependencies
      run: npm ci

    - name: Start
      run: npm start
      env:
        RWAPI_APPNAME: ${{ secrets.RWAPI_APPNAME }}

    - name: Commit
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data.csv
          git commit -m "chore: Data generated"
          git push

    - name: Get current date
      id: date
      run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Upload to gdrive
      uses: mathisve/gdrive-upload-action@main
      with:
        filename: data.csv
        name: data-${{ env.NOW }}.csv
        folderId: 0B3AvU8yMBJnEWk9EQmR1OXVIdVU
        credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
        encoded: true
        overwrite: true
